### ISSUE TITLE
Read a lot of docs and do something else than program and discuss

### ISSUE THREAD

**Issue by n-peugnet** [slipsoft/slipdb#14]
so that I can rest

**Comment by SylvainLune** [comment]
I'm going to make the IndexTree working with the disk, and multithread !! :D (soon...)
Hope it will work...
Rest In Peace, Nicolas...
(may not work and fry my brain forever...)

**Comment by SylvainLune** [comment]
I'm going to make the IndexTree working with the disk, and multithread !! :D (soon...)
Hope it will work...
Rest In Peace, Nicolas, I'll come for You...
(may not work and fry my brain forever howerver...)
(probably will fry my brain, indeed...)

**Comment by n-peugnet** [comment]
En vrai mec ça serait vraiment le plus important. Je sais que tu n'as pas cette habitude mais tu devrais grave requarder comment sql ou autre stockent leurs index plutôt que d'essayer de réinventer un nouveau système.

**Comment by n-peugnet** [comment]
Parce que là tout à l'heure j'en ai parlé un peu avec un collèque et par exemple le fait de faire un zoom dans le fichier d'index en resserant petit à petit l'étau ça s'appelle la dichotomie et je pense que si tu cherche un peu store tree dichotomy sur internet tu as des milliers de resultats (en vrai j'ai même pas testé)

**Comment by SylvainLune** [comment]
J'avoue que vu que le faire par dichotomie, c'est quand-même pas con, vu que les entrées d'un TreeMap sont classées par valeur croissante ^-^
Faudra que je regarde ça et que je regarde d'autres trucs sur le même sujet, aussi ^^

**Comment by SylvainLune** [comment]
J'avoue que vu que le faire par dichotomie, c'est quand-même pas con, vu que les entrées d'un TreeMap sont classées par valeur croissante ^-^
Faudra que je regarde ça et que je regarde d'autres trucs sur le même sujet, aussi ^^
