### ISSUE TITLE
Is it really ok ?

### ISSUE THREAD

**Issue by n-peugnet** [slipsoft/slipdb#86]
https://github.com/slipsoft/slipdb/blob/95568359f833a974cf8d866baf660f4cb6544e16/src/main/java/index/memDic/IndexMemDicAncester.java#L14

@SylvainLune T'es sûr que ça doit être static ça ?

**Comment by n-peugnet** [comment]
déso d'avoir fait une issue pour ça mais j'ai pas réussi à faire juste un commentaire.

**Comment by SylvainLune** [comment]
Ah oui, effectivement, il faut que je modifie le code pour permettre à la fois la sauvegarde en statique des variables utiles au sort de indexMemDic et à la fois permettre d'avoir plus de 1 seul index x'D

Je vais mettre à jour ça dans une prochaine PR ! (y a pas "juste" le static à changer ^^)

**Comment by SylvainLune** [comment]
J'ai fait la PR, bug réparé ! Merci beaucoup Nicauw :)

**Comment by n-peugnet** [comment]
Yes c'est bon c'est mergé. Et avec un peu de chance ya meme pas de conflits avec la mienne
